docs: 22-restructure-document-following-iso-style
eclipse-dataspace-protocol-base/DataspaceProtocol pull request #58
Opened 2024-11-19 09:35 UTC by ssteinbuss

## What this PR changes/adds

Adding mandatory sections as required by ISO style:

* Foreword
* Introduction
* Scope
* normative references
* Terms and definitions

## Why it does that

ISO style is targeted for the document

## Further notes

index.md for respec is updated accordingly. 

## Linked Issue(s)

Closes # <-- _insert issue number if one exists_

_Please be sure to take a look at the [contributing guidelines](../CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](../PR_ETIQUETTE.md)._

2024-11-19 14:45 UTC, arnoweiss requested changes
Reach out if there's further explanation needed.

2024-11-19 14:45 UTC, arnoweiss commented on model/terminology.md
> +# Terms and definitions
```suggestion
# Terms and definitions {#terminology}
```
preserves the backward compatibility of existing references pointing to the `terminology` section.

2024-11-19 14:45 UTC, arnoweiss commented on README.md
> -1. How [Datasets](./model/terminology.md#dataset) are deployed as [DCAT Catalogs](https://www.w3.org/TR/vocab-dcat-3/#Class:Catalog) and usage control is expressed as [ODRL Policies](https://www.w3.o
General comment: Definitions should be referenced with the `[=Term=]` mechanism as outlined in [`WEBSITE.md`](https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/blob/main/WEBSITE.md)

2024-11-19 14:45 UTC, arnoweiss commented on index.html
> +<section data-include="normative.references.md" data-include-format="markdown">
There's already an autogenerated References section at the end of the document. If it's a requirement to have it at the start, please open an issue in this repository. We might have to build a separate respec profile instead of reusing the w3c (as currently).

2024-11-19 14:55 UTC, jimmarino commented
@ssteinbuss Sorry I accidentally committed @arnoweiss suggestion. I hit the wrong button. Can you revert it?

2024-11-20 07:31 UTC, ssteinbuss commented on index.html
> +<section data-include="normative.references.md" data-include-format="markdown">
Those are different sections. The normative references section is mandatory in the ISO template and uses a standard text and references to other ISO/IEC standards. The references section in the end should be kept there.

2024-11-28 09:50 UTC, arnoweiss approved these changes
I'll go ahead and fix the review comments in a separate PR. Thanks for creating the new issue.

2024-11-28 09:51 UTC, ssteinbuss commented
@jimmarino can you approve please?

2024-11-28 10:19 UTC, jimmarino approved these changes

2024-11-28 12:42 UTC, merged